const CRYPTO_QUERY_KEY = "crypto"
const TREND_CRYPTO_QUERY_KEY = "trend_crypto"
const CRYPTO_HISTORICAL_PRICE_QUERY_KEY = "crypto_historical_price"
const TOP_LIST_QUERY_KEY = "top_list"


export {CRYPTO_QUERY_KEY, TREND_CRYPTO_QUERY_KEY, CRYPTO_HISTORICAL_PRICE_QUERY_KEY, TOP_LIST_QUERY_KEY}